export const HYDRATE = "HYDRATE";

export const TOGGLE_TAB = "TOGGLE_TAB";

export const UPDATE_CONFIG_VALUE = "UPDATE_CONFIG_VALUE";
export const UPDATE_CONFIG_CURSOR = "UPDATE_CONFIG_CURSOR";
export const UPDATE_CONFIG_SELECTION = "UPDATE_CONFIG_SELECTION";

export const REQUEST_DEFAULT_CONFIG_VALUE = "REQUEST_DEFAULT_CONFIG_VALUE";
export const RECEIVE_DEFAULT_CONFIG_VALUE = "RECEIVE_DEFAULT_CONFIG_VALUE";

export const UPDATE_CONTENT_VALUE = "UPDATE_CONTENT_VALUE";
export const UPDATE_CONTENT_CURSOR = "UPDATE_CONTENT_CURSOR";
export const UPDATE_CONTENT_SELECTION = "UPDATE_CONTENT_SELECTION";

export const REQUEST_DEFAULT_CONTENT_VALUE = "REQUEST_DEFAULT_CONTENT_VALUE";
export const RECEIVE_DEFAULT_CONTENT_VALUE = "RECEIVE_DEFAULT_CONTENT_VALUE";
